apiVersion: batch/v1
kind: CronJob
metadata:
  name: nfl-fetcher-cronjob
spec:
  schedule: "0 3 * * *" # runs every hour or (*/1 * * * *) for every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nfl-fetcher
              image: md1054470/nfl-fetcher:latest
              imagePullPolicy: Always
              env:
                - name: MONGO_URI
                  value: "mongodb://mongo-service:27017/nfl"
                - name: NFL_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: nfl-api-secret
                      key: NFL_API_KEY
          restartPolicy: OnFailure
